// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kteugklaysicmpdxmtpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0ZXVna2xheXNpY21wZHhtdHB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyODgzNTksImV4cCI6MjA2Nzg2NDM1OX0.UD13EHMxo2Mm3m9yqruzMeCF3JOpL9wZD-zlqbY3Y70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});